### PR TITLE
Use ec2_metadata since boto no longer works

### LINKED ISSUE #3640: Investigate Staging Failures
App VMs are crashing with this message:

```
Aug 01 19:33:43 ip-10-0-3-162 systemd[1]: Starting mmw-app...
Aug 01 19:33:43 ip-10-0-3-162 systemd[1]: Started mmw-app.
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]: Traceback (most recent call last):
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/bin/gunicorn", line 8, in <module>
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     sys.exit(run())
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 231, in run
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     super().run()
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 72, in run
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     Arbiter(self).run()
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 58, in __init__
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     self.setup(app)
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 118, in setup
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     self.app.wsgi()
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     self.callable = self.load()
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     return self.load_wsgiapp()
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     return util.import_app(self.app_uri)
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     mod = importlib.import_module(module)
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:     return _bootstrap._gcd_import(name[level:], package, level)
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Aug 01 19:34:05 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "/opt/app/mmw/__init__.py", line 3, in <module>
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:     from .celery import app as celery_app
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "/opt/app/mmw/celery.py", line 21, in <module>
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:     rollbar_settings = getattr(settings, 'ROLLBAR', {})
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 82, in __getattr__
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:     self._setup(name)
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 69, in _setup
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:     self._wrapped = Settings(settings_module)
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 170, in __init__
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:     mod = importlib.import_module(self.SETTINGS_MODULE)
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:     return _bootstrap._gcd_import(name[level:], package, level)
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:   File "/opt/app/mmw/settings/production.py", line 21, in <module>
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]:     raise ImproperlyConfigured('Unable to access the instance metadata')
Aug 01 19:34:06 ip-10-0-3-162 gunicorn[415]: django.core.exceptions.ImproperlyConfigured: Unable to access the instance metadata
Aug 01 19:34:06 ip-10-0-3-162 systemd[1]: mmw-app.service: Main process exited, code=exited, status=1/FAILURE
Aug 01 19:34:06 ip-10-0-3-162 systemd[1]: mmw-app.service: Failed with result 'exit-code'.
```

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

See https://github.com/azavea/cac-tripplanner/pull/1377, azavea/mub-monitor#853, and boto/boto3#313

Closes #3640 

### Demo

https://staging.modelmywatershed.org/

## Testing Instructions

- Go to staging
  - [x] Ensure it loads properly
- Run Global Land 2023 analysis
  - [x] Ensure it runs properly

### CODE REVIEW

File: src/mmw/js/src/modeling/tests.js [hunk 1]
```diff
@@ -834,7 +834,8 @@ describe('Modeling', function() {
                 });
 
                 function fetchResultsAssertions(self) {
-                    assert(inputModSpy.calledTwice, 'updateInputModHash should have been called twice');
+                    // TODO: Re-enable tests https://github.com/WikiWatershed/model-my-watershed/issues/3442
```
Comment (rajadain) [inline src/mmw/js/src/modeling/tests.js:837]: These tests are flaky and will often fail. Disabling them for now, to be re-enabled in #3442.

**Review by rachelekm — APPROVED** [review]
Staging looks good and these changes are in line with other projects 👍

**Comment by rajadain** [comment]
Thanks for taking a look!
