### PR TITLE
Fix tab switching issues

### LINKED ISSUE #164: Fix scenario drop-down menu
It doesn't quite work in the prototypes.

It's currently activating the correct scenario toolbar, but it 1) doesn't activate the scenario tab and 2) doesn't clear the active class from a menu item when another menu item is selected. 

selection_016

### PR DESCRIPTION
**Pull request by kdeloach**
Replaces usage of `slug` with `cid` throughout. This fixes an edge case
where tabs could fall out of sync with their tab panels when the `slug`
changed.

Ex.
image

This also defines a standard way of setting the active tab by using
a method on the `ScenariosCollection` called `setActiveScenario`.

Fixes #164

### CODE REVIEW

**Comment by caseypt** [comment]
Nice work. Going to test this out now.

We should also remove this line: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/controllers.js#L37

**Comment by kdeloach** [comment]
Do you think it makes more sense to have "area of interest" on the Project model or the Map model? I was leaning towards Project.

**Comment by caseypt** [comment]
Yeah, I think it now makes more sense to have this on  project. Though that would involve us creating the Project model sooner. But I think that makes more sense too.

File: src/mmw/js/src/modeling/models.js [hunk 1]
```diff
@@ -82,27 +91,30 @@ var ProjectModel = Backbone.Model.extend({
...
+        return slug;
     }
 });
 
 var ScenariosCollection = Backbone.Collection.extend({
     model: ScenarioModel,
-    comparator: 'created_at'
+    comparator: 'created_at',
+
+    setActiveScenario: function(cid) {
```
Comment (caseypt) [inline src/mmw/js/src/modeling/models.js]: +1 to custom collection methods for stuff like this.

**Comment by caseypt** [comment]
+1. Tested. Works. I was able to generate a bunch of scenarios and switch between them, as well as rename some of the scenarios and have the tabs still work.

**Comment by mmcfarland** [comment]
+1 Looks good.  I discussed a similar implementation with @lliss on friday, so you may want to check this out.
